apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yaam1ypi4-nodejs 
  janus-idp.io/tekton: yaam1ypi4-nodejs
  backstage.io/kubernetes-id: yaam1ypi4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yaam1ypi4-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml